#!/bin/sh
set -e

#DEBHELPER#

if [ "$1" = "remove" ]; then
    # Stop the timers and service before removal
    deb-systemd-invoke stop aptupdatechecker_apt_update_checker.timer || true
    deb-systemd-invoke stop aptupdatechecker_firmware_update_checker.timer || true
    deb-systemd-invoke stop aptupdatechecker_autoclean.timer || true
    deb-systemd-invoke stop aptupdatechecker_autoremove.timer || true
    deb-systemd-invoke stop aptupdatechecker.service || true
fi

exit 0
